name: Copy merge-pdf to drobilica.github.io

on:
  push:
    branches:
      - main

env:
  TARGET_REPO: drobilica/drobilica.github.io
  TARGET_PATH: drobilica-homepage
  TARGET_FOLDER: merge-pdf

jobs:
  copy_merge_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout merge-pdf repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main

      - name: Sync Folder to Repository B
        uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPO }}
          token: ${{ secrets.drobilica_access }}
          path: ${{ env.TARGET_PATH }}

      - name: Copy Files
        run: |
          mkdir -p ${{ env.TARGET_PATH }}/${{ env.TARGET_FOLDER }}
          rm -rf ${{ env.TARGET_PATH }}/${{ env.TARGET_FOLDER }}/*
          shopt -s extglob # Enable extended globbing
          cp -R !( "${{ env.TARGET_PATH }}" ) ${{ env.TARGET_PATH }}/${{ env.TARGET_FOLDER }}
          shopt -u extglob # Disable extended globbing

      - name: Copy merge-pdf contents to drobilica.github.io
        run: |
          cd ${{ env.TARGET_PATH }}
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update from PDF-merge"
          git push
